reflections = {
    "tôi là": "bạn là",
    "mình là": "bạn là",
    "tao là": "bạn là",
    "anh là": "anh là",
    "chị là": "chị là",
    "bà là": "bà là",
    "ông là": "ông là",
    "tôi đang": "bạn đang",
    "mình đang": "bạn đang",
    "anh đang": "bạn đang",
    "chị đang": "chị đang",
    "tôi có": "bạn có",
    "anh có": "anh có",
    "chị có": "chị có",
    "của tôi": "của bạn",
    "của anh": "của anh",
    "của chị": "của chị",
    "tôi": "bạn",
    "anh": "anh",
    "chị": "chị",

    "i was": "you were",
    "i": "you",
    "i'm": "you are",
    "i'd": "you would",
    "i've": "you have",
    "i'll": "you will",
    "my": "your",
    "you are": "I am",
    "you were": "I was",
    "you've": "I have",
    "you'll": "I will",
    "your": "my",
    "yours": "mine",
    "you": "me",
    "me": "you"
}